//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _STREETSWEEPER_H_
#define _STREETSWEEPER_H_

#include <TinyCLR_Interop.h>
struct Library_StreetSweeper_MakeItRobotics_Program
{
    static const int FIELD_STATIC__street_sweeper = 0;
    static const int FIELD_STATIC__valueo = 1;
    static const int FIELD_STATIC__valuen = 2;
    static const int FIELD_STATIC__sweep = 3;


    //--//

};

struct Library_StreetSweeper_MakeItRobotics_Resources
{
    static const int FIELD_STATIC__manager = 4;


    //--//

};

struct Library_StreetSweeper_MakeItRobotics_StreetSweeper
{
    static const int FIELD__irDataHigh = 1;
    static const int FIELD__irDataLow = 2;
    static const int FIELD__irBits = 3;
    static const int FIELD__irRxFlag = 4;
    static const int FIELD__current_IR_time = 5;
    static const int FIELD__diff_IR_time = 6;
    static const int FIELD__last_IR_time = 7;
    static const int FIELD__OirDataHigh = 8;
    static const int FIELD__OirDataLow = 9;
    static const int FIELD__CirDataHigh = 10;
    static const int FIELD__CirDataLow = 11;
    static const int FIELD__even = 12;
    static const int FIELD__repeatTimer1 = 13;
    static const int FIELD__repeatTimer2 = 14;
    static const int FIELD__startTicks = 15;
    static const int FIELD__serial = 16;
    static const int FIELD__remotePin = 17;


    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_StreetSweeper;

#endif  //_STREETSWEEPER_H_
